# -*- coding: utf-8 -*-
"""streamlit_imagindata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T_P50jsy4XBqe_DMLVNmY1FoAPRNbIb9
"""


import streamlit as st
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
import requests
from googletrans import Translator
import random 


#Définir le thème personnalisé

st.set_page_config(page_title="🎥 App de Recommandation de films", page_icon=":🎞️:", layout="wide", initial_sidebar_state="expanded")


# TITRE
st.title("🎥 App de Recommandation de films")

# SOUS TITRE
st.header("Dis moi quels sont tes goûts et je te ferai découvrir de nouveaux films 💡🎬")



#Fonction pour traduire le texte
def translate_page(page_content, target_language='en'):
    translator = Translator()
    translated_content = translator.translate(page_content, dest=target_language)
    return translated_content.text

def main():
    st.title("App de Recommandation de films")

    # Contenu initial
    page_content = """
    Bienvenue dans cette application de recommandation de films.
    Essayez de cliquer sur le bouton de traduction pour voir le contenu dans une autre langue!
    """

    # Affichage du contenu initial
    st.markdown(page_content)

    # Bouton de traduction
    if st.button("Traduire en anglais"):
        translated_content = translate_page(page_content, target_language='en')
        st.markdown(translated_content)

if __name__ == "__main__":
    main()

#CHARGER LES DATAFRAMES
    
#Remplacez l'URL par l'URL brute de votre fichier CSV sur GitHub
#Charger le fichier CSV dans un DataFrame
df_KNN = pd.read_csv("https://raw.githubusercontent.com/IMAGINEDATA1/APP/main/t_KNN")


# Création d'une barre de recherche avec autocomplétion et KNN


# Création de la recommandation basée sur KNN


# Créer une barre de recherche avec autocomplétion

# Utilisateur saisit nom du film
user_input_film = st.text_input("Tapez votre recherche", " ")

# Check si nom du film est dans le df
if user_input_film in df_KNN['primaryTitle'].values:
    # Extraire les caractéristiques du film saisi par l'utilisateur
    user_film_features = df_KNN.loc[df_KNN['primaryTitle'] == user_input_film, ['startYear', 'original_language', 'Action', 'Adventure', 'Biography', 'Crime', 'Mystery']]

    # Entraîner le modèle sur l'ensemble complet des caractéristiques
    X_all = df_KNN[['startYear', 'original_language', 'Action', 'Adventure', 'Biography', 'Crime', 'Mystery']].values
    modelNN = NearestNeighbors(n_neighbors=5)
    modelNN.fit(X_all)

    # Définition des voisins les plus proches du film saisi par l'utilisateur
    neighbors = modelNN.kneighbors(user_film_features.values)
    neighbors_indices = neighbors[1][0]

    # Filtrer les voisins pour ne prendre que ceux avec le même 'original_language'
    user_language = user_film_features['original_language'].values[0]
    filtered_neighbors_indices = [index for index in neighbors_indices if df_KNN.loc[index, 'original_language'] == user_language]

    # Exclusion du film saisi par l'utilisateur de la liste des recommandations
    filtered_neighbors_indices = [index for index in filtered_neighbors_indices if index != df_KNN[df_KNN['primaryTitle'] == user_input_film].index[0]]

    # Résultats recommandations
    neighbors_names = df_KNN['primaryTitle'].iloc[filtered_neighbors_indices]

    # Afficher les résultats de manière structurée
    st.subheader(f"Résultats de recommandation pour '{user_input_film}':")
    for i, movie_title in enumerate(neighbors_names, start=1):
        st.write(f"{i}. {movie_title}")

else:
    # Si le film n'a pas été trouvé
    st.write(f"\nLe film '{user_input_film}' n'a pas été trouvé dans la base de données.")

    # 4 films choisis aléatoirement comme recommandations
    random_recos = random.sample(df_KNN['primaryTitle'].tolist(), 4)

    st.write("Vous ne trouvez pas ? Voici quelques unes de mes idées :")
    for i, movie_title in enumerate(random_recos, start=1):
        st.write(f"{i}. {movie_title}")


#REQUETE API 

# Fonction pour obtenir les informations d'un film à partir de l'API TMDb
def get_movie_details(movie_id):
    api_key = "db38952c66997974559ef641200fc25e"
    base_url = "https://api.themoviedb.org/3/movie/"
    endpoint = str(movie_id)
    url = f"{base_url}{endpoint}?api_key={api_key}"

    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        return None

# Utilisation de la fonction dans le contexte de votre script
user_input_film = st.text_input("Tapez votre recherche", " ") 
movie_details = get_movie_details(user_input_film)

if movie_details:
    # Afficher l'image du film
    poster_path = movie_details.get('poster_path')
    if poster_path:
        st.image(f"https://image.tmdb.org/t/p/w500/{poster_path}", caption=movie_details.get('title'), use_column_width=True)

    # Afficher d'autres détails du film
    st.markdown(f"**Titre:** {movie_details.get('title')}")
    st.markdown(f"**Tagline:** {movie_details.get('tagline')}")
    st.markdown(f"**Aperçu:** {movie_details.get('overview')}")

    # Afficher d'autres détails du film (Note IMDb, nombre de votes, durée, genre, acteurs, réalisateurs)
    st.write(f"**Note IMDb:** {movie_details.get('averageRating')}")
    st.write(f"**Nombre de votes:** {movie_details.get('vote_count')}")
    st.write(f"**Durée:** {movie_details.get('runtimeMinutes')} minutes")
    st.write(f"**Genre:** {', '.join([genre['primaryName'] for genre in movie_details.get('genre1', [])])}")

    # Acteurs
    st.write("**Acteurs:**")
    cast_members = movie_details.get('credits', {}).get('cast', [])[:3]
    for cast_member in cast_members:
        st.write(f"- {cast_member.get('primaryName')}")

    # Réalisateurs
    st.write("**Réalisateurs:**")
    crew_members = movie_details.get('credits', {}).get('crew', [])
    directors = [crew_member.get('primaryName') for crew_member in crew_members if crew_member.get('job') == 'Director']
    for director in directors:
        st.write(f"- {director}")
else:
    st.info("Film non trouvé ou erreur lors de la récupération des détails.")


# SOUS-TITRE
st.subheader("Bonne séance ! 🍿🍿🍿 ")
