[theme]

primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#DCDCDC"
font = "sans-serif"
background-image = radial-gradient(#444cf7 0.5px, #e5e5f7 0.5px)
background-size = 10px 10px
